export { Colors, HighContrast } from "./theme/colors"
export { Typography } from "./theme/typography"
export { Spacing, Radius } from "./theme/spacing"

export { BOX_CHARS, createBox, createBoxWithTitle, createPanel } from "./renderer/box"
export type { BoxStyle, BoxOptions } from "./renderer/box"
export * as Text from "./renderer/text"
export * as Gradient from "./renderer/gradient"
export * as Animation from "./renderer/animation"

export { ActivityCard } from "./components/activity-card"
export type { ActivityCardProps, ActivityStatus } from "./components/activity-card"
export { StatusIndicator } from "./components/status-indicator"
export type { StatusIndicatorProps, IndicatorStatus } from "./components/status-indicator"
export { MemoryWidget } from "./components/memory-widget"
export type { MemoryWidgetProps } from "./components/memory-widget"
export { AgentPanel } from "./components/agent-panel"
export type { AgentInfo, AgentStatusPanelProps } from "./components/agent-panel"
export { ProgressBar } from "./components/progress-bar"
export type { ProgressBarProps, ProgressStyle } from "./components/progress-bar"
export { CommandPalette } from "./components/command-palette"
export type { CommandPaletteProps } from "./components/command-palette"

export { MainView } from "./layout/main-view"
export type { MainViewOptions, HeaderInfo } from "./layout/main-view"
export { SplitView } from "./layout/split-view"
export type { SplitViewOptions } from "./layout/split-view"
export { Responsive } from "./layout/responsive"
export type { LayoutMode, LayoutConfig } from "./layout/responsive"

export * as Format from "./format"
